# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07pdfchat\"9\n\x10UploadPDFRequest\x12\x10\n\x08pdf_name\x18\x01 \x01(\t\x12\x13\n\x0bpdf_content\x18\x02 \x01(\x0c\"#\n\x11UploadPDFResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"&\n\x12\x41skQuestionRequest\x12\x10\n\x08question\x18\x01 \x01(\t\"%\n\x13\x41skQuestionResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2\x9a\x01\n\nPDFService\x12\x42\n\tUploadPDF\x12\x19.pdfchat.UploadPDFRequest\x1a\x1a.pdfchat.UploadPDFResponse\x12H\n\x0b\x41skQuestion\x12\x1b.pdfchat.AskQuestionRequest\x1a\x1c.pdfchat.AskQuestionResponseB:Z8github.com/ManoVikram/AI-PDF-Chat/backend/go-api/pdfchatb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/ManoVikram/AI-PDF-Chat/backend/go-api/pdfchat'
  _globals['_UPLOADPDFREQUEST']._serialized_start=26
  _globals['_UPLOADPDFREQUEST']._serialized_end=83
  _globals['_UPLOADPDFRESPONSE']._serialized_start=85
  _globals['_UPLOADPDFRESPONSE']._serialized_end=120
  _globals['_ASKQUESTIONREQUEST']._serialized_start=122
  _globals['_ASKQUESTIONREQUEST']._serialized_end=160
  _globals['_ASKQUESTIONRESPONSE']._serialized_start=162
  _globals['_ASKQUESTIONRESPONSE']._serialized_end=199
  _globals['_PDFSERVICE']._serialized_start=202
  _globals['_PDFSERVICE']._serialized_end=356
# @@protoc_insertion_point(module_scope)
