# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PDFServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadPDF = channel.unary_unary(
                '/pdfchat.PDFService/UploadPDF',
                request_serializer=service__pb2.UploadPDFRequest.SerializeToString,
                response_deserializer=service__pb2.UploadPDFResponse.FromString,
                _registered_method=True)
        self.AskQuestion = channel.unary_unary(
                '/pdfchat.PDFService/AskQuestion',
                request_serializer=service__pb2.AskQuestionRequest.SerializeToString,
                response_deserializer=service__pb2.AskQuestionResponse.FromString,
                _registered_method=True)


class PDFServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadPDF(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AskQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PDFServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadPDF': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadPDF,
                    request_deserializer=service__pb2.UploadPDFRequest.FromString,
                    response_serializer=service__pb2.UploadPDFResponse.SerializeToString,
            ),
            'AskQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.AskQuestion,
                    request_deserializer=service__pb2.AskQuestionRequest.FromString,
                    response_serializer=service__pb2.AskQuestionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pdfchat.PDFService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pdfchat.PDFService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PDFService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadPDF(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pdfchat.PDFService/UploadPDF',
            service__pb2.UploadPDFRequest.SerializeToString,
            service__pb2.UploadPDFResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AskQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pdfchat.PDFService/AskQuestion',
            service__pb2.AskQuestionRequest.SerializeToString,
            service__pb2.AskQuestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
