// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: service.proto

package pdfchat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PDFService_UploadPDF_FullMethodName   = "/pdfchat.PDFService/UploadPDF"
	PDFService_AskQuestion_FullMethodName = "/pdfchat.PDFService/AskQuestion"
)

// PDFServiceClient is the client API for PDFService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PDFServiceClient interface {
	UploadPDF(ctx context.Context, in *UploadPDFRequest, opts ...grpc.CallOption) (*UploadPDFResponse, error)
	AskQuestion(ctx context.Context, in *AskQuestionRequest, opts ...grpc.CallOption) (*AskQuestionResponse, error)
}

type pDFServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPDFServiceClient(cc grpc.ClientConnInterface) PDFServiceClient {
	return &pDFServiceClient{cc}
}

func (c *pDFServiceClient) UploadPDF(ctx context.Context, in *UploadPDFRequest, opts ...grpc.CallOption) (*UploadPDFResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadPDFResponse)
	err := c.cc.Invoke(ctx, PDFService_UploadPDF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pDFServiceClient) AskQuestion(ctx context.Context, in *AskQuestionRequest, opts ...grpc.CallOption) (*AskQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AskQuestionResponse)
	err := c.cc.Invoke(ctx, PDFService_AskQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PDFServiceServer is the server API for PDFService service.
// All implementations must embed UnimplementedPDFServiceServer
// for forward compatibility.
type PDFServiceServer interface {
	UploadPDF(context.Context, *UploadPDFRequest) (*UploadPDFResponse, error)
	AskQuestion(context.Context, *AskQuestionRequest) (*AskQuestionResponse, error)
	mustEmbedUnimplementedPDFServiceServer()
}

// UnimplementedPDFServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPDFServiceServer struct{}

func (UnimplementedPDFServiceServer) UploadPDF(context.Context, *UploadPDFRequest) (*UploadPDFResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadPDF not implemented")
}
func (UnimplementedPDFServiceServer) AskQuestion(context.Context, *AskQuestionRequest) (*AskQuestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AskQuestion not implemented")
}
func (UnimplementedPDFServiceServer) mustEmbedUnimplementedPDFServiceServer() {}
func (UnimplementedPDFServiceServer) testEmbeddedByValue()                    {}

// UnsafePDFServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PDFServiceServer will
// result in compilation errors.
type UnsafePDFServiceServer interface {
	mustEmbedUnimplementedPDFServiceServer()
}

func RegisterPDFServiceServer(s grpc.ServiceRegistrar, srv PDFServiceServer) {
	// If the following call pancis, it indicates UnimplementedPDFServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PDFService_ServiceDesc, srv)
}

func _PDFService_UploadPDF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadPDFRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PDFServiceServer).UploadPDF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PDFService_UploadPDF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PDFServiceServer).UploadPDF(ctx, req.(*UploadPDFRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PDFService_AskQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PDFServiceServer).AskQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PDFService_AskQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PDFServiceServer).AskQuestion(ctx, req.(*AskQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PDFService_ServiceDesc is the grpc.ServiceDesc for PDFService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PDFService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pdfchat.PDFService",
	HandlerType: (*PDFServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadPDF",
			Handler:    _PDFService_UploadPDF_Handler,
		},
		{
			MethodName: "AskQuestion",
			Handler:    _PDFService_AskQuestion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
